/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GamesRouteImport } from './routes/games'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesDueldleIndexRouteImport } from './routes/games/dueldle/index'
import { Route as Games64rdleIndexRouteImport } from './routes/games/64rdle/index'
import { Route as GamesDueldleGameRouteImport } from './routes/games/dueldle/game'

const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDueldleIndexRoute = GamesDueldleIndexRouteImport.update({
  id: '/dueldle/',
  path: '/dueldle/',
  getParentRoute: () => GamesRoute,
} as any)
const Games64rdleIndexRoute = Games64rdleIndexRouteImport.update({
  id: '/64rdle/',
  path: '/64rdle/',
  getParentRoute: () => GamesRoute,
} as any)
const GamesDueldleGameRoute = GamesDueldleGameRouteImport.update({
  id: '/dueldle/game',
  path: '/dueldle/game',
  getParentRoute: () => GamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games': typeof GamesRouteWithChildren
  '/games/dueldle/game': typeof GamesDueldleGameRoute
  '/games/64rdle/': typeof Games64rdleIndexRoute
  '/games/dueldle/': typeof GamesDueldleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games': typeof GamesRouteWithChildren
  '/games/dueldle/game': typeof GamesDueldleGameRoute
  '/games/64rdle': typeof Games64rdleIndexRoute
  '/games/dueldle': typeof GamesDueldleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games': typeof GamesRouteWithChildren
  '/games/dueldle/game': typeof GamesDueldleGameRoute
  '/games/64rdle/': typeof Games64rdleIndexRoute
  '/games/dueldle/': typeof GamesDueldleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games'
    | '/games/dueldle/game'
    | '/games/64rdle/'
    | '/games/dueldle/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games'
    | '/games/dueldle/game'
    | '/games/64rdle'
    | '/games/dueldle'
  id:
    | '__root__'
    | '/'
    | '/games'
    | '/games/dueldle/game'
    | '/games/64rdle/'
    | '/games/dueldle/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesRoute: typeof GamesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/dueldle/': {
      id: '/games/dueldle/'
      path: '/dueldle'
      fullPath: '/games/dueldle/'
      preLoaderRoute: typeof GamesDueldleIndexRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/64rdle/': {
      id: '/games/64rdle/'
      path: '/64rdle'
      fullPath: '/games/64rdle/'
      preLoaderRoute: typeof Games64rdleIndexRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/dueldle/game': {
      id: '/games/dueldle/game'
      path: '/dueldle/game'
      fullPath: '/games/dueldle/game'
      preLoaderRoute: typeof GamesDueldleGameRouteImport
      parentRoute: typeof GamesRoute
    }
  }
}

interface GamesRouteChildren {
  GamesDueldleGameRoute: typeof GamesDueldleGameRoute
  Games64rdleIndexRoute: typeof Games64rdleIndexRoute
  GamesDueldleIndexRoute: typeof GamesDueldleIndexRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesDueldleGameRoute: GamesDueldleGameRoute,
  Games64rdleIndexRoute: Games64rdleIndexRoute,
  GamesDueldleIndexRoute: GamesDueldleIndexRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesRoute: GamesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
