/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R64rdleRouteImport } from './routes/64rdle'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DueldleIndexRouteImport } from './routes/dueldle/index'
import { Route as DueldleGameRouteImport } from './routes/dueldle/game'

const R64rdleRoute = R64rdleRouteImport.update({
  id: '/64rdle',
  path: '/64rdle',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DueldleIndexRoute = DueldleIndexRouteImport.update({
  id: '/dueldle/',
  path: '/dueldle/',
  getParentRoute: () => rootRouteImport,
} as any)
const DueldleGameRoute = DueldleGameRouteImport.update({
  id: '/dueldle/game',
  path: '/dueldle/game',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/64rdle': typeof R64rdleRoute
  '/dueldle/game': typeof DueldleGameRoute
  '/dueldle/': typeof DueldleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/64rdle': typeof R64rdleRoute
  '/dueldle/game': typeof DueldleGameRoute
  '/dueldle': typeof DueldleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/64rdle': typeof R64rdleRoute
  '/dueldle/game': typeof DueldleGameRoute
  '/dueldle/': typeof DueldleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/64rdle' | '/dueldle/game' | '/dueldle/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/64rdle' | '/dueldle/game' | '/dueldle'
  id: '__root__' | '/' | '/64rdle' | '/dueldle/game' | '/dueldle/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R64rdleRoute: typeof R64rdleRoute
  DueldleGameRoute: typeof DueldleGameRoute
  DueldleIndexRoute: typeof DueldleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/64rdle': {
      id: '/64rdle'
      path: '/64rdle'
      fullPath: '/64rdle'
      preLoaderRoute: typeof R64rdleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dueldle/': {
      id: '/dueldle/'
      path: '/dueldle'
      fullPath: '/dueldle/'
      preLoaderRoute: typeof DueldleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dueldle/game': {
      id: '/dueldle/game'
      path: '/dueldle/game'
      fullPath: '/dueldle/game'
      preLoaderRoute: typeof DueldleGameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R64rdleRoute: R64rdleRoute,
  DueldleGameRoute: DueldleGameRoute,
  DueldleIndexRoute: DueldleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
